# Generated by Django 4.1.3 on 2022-11-11 00:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0002_alter_storage_owner_storage_higher_level_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Storage_Owner',
            new_name='StorageOwner',
        ),
        migrations.AlterModelTable(
            name='storageowner',
            table='storage_owner',
        ),
    ]
