# Generated by Django 4.1.3 on 2022-11-11 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_rename_storage_owner_storageowner_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='storage',
            table='storages',
        ),
        migrations.AlterModelTable(
            name='storageowner',
            table='storages_owner',
        ),
    ]
