# Generated by Django 4.1.3 on 2022-11-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_storageaction_storagemodification'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagemodification',
            name='visible_all',
            field=models.BooleanField(default=False),
        ),
    ]
