# Generated by Django 4.1.3 on 2022-11-12 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_storagemodification_visible_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageaction',
            name='codename',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='storagemodification',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storageaction', to_field='codename'),
        ),
    ]
