# Generated by Django 4.1.3 on 2022-11-12 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_rename_action_storagemodification_action_codename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagemodification',
            name='action_codename',
        ),
        migrations.AddField(
            model_name='storagemodification',
            name='action',
            field=models.ForeignKey(default='action_codename', on_delete=django.db.models.deletion.CASCADE, to='stores.storageaction', to_field='codename'),
        ),
    ]
