# Generated by Django 4.1.3 on 2022-11-12 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_rename_action_storagemodification_actioned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemodification',
            name='actioned',
            field=models.ForeignKey(db_column='action_codename', on_delete=django.db.models.deletion.CASCADE, to='stores.storageaction', to_field='codename'),
        ),
    ]
