# Generated by Django 4.1.3 on 2022-11-12 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_alter_storagemodification_actioned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagemodification',
            old_name='actioned',
            new_name='action',
        ),
    ]
