# Generated by Django 4.1.3 on 2022-11-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_rename_actioned_storagemodification_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagemodification',
            old_name='action',
            new_name='action_codename',
        ),
        migrations.AddField(
            model_name='storage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
