# Generated by Django 4.1.3 on 2022-11-12 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_rename_action_storagemodification_action_codename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='content',
        ),
    ]
