# Generated by Django 4.1.3 on 2022-11-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_remove_storage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageowner',
            name='storage_root_id',
            field=models.IntegerField(default=True),
        ),
    ]
