# Generated by Django 4.1.3 on 2022-11-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_alter_storageowner_storage_root_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageowner',
            name='storage_root_id',
        ),
    ]
