# Generated by Django 4.1.3 on 2022-12-19 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_storageshare_storagesharestorage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storageshare',
            old_name='from_user',
            new_name='from_user_id',
        ),
        migrations.RenameField(
            model_name='storageshare',
            old_name='to_user',
            new_name='to_user_id',
        ),
    ]
