# Generated by Django 4.1.3 on 2023-05-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0020_storageonlineeditors'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageonlineeditors',
            name='sid',
            field=models.TextField(default=''),
        ),
    ]
